### ISSUE TITLE
Save labyrinthe

### ISSUE THREAD

**Issue by SneakDiffer** [Usanter/RobotLegoMazeSolver#10]
Il faut enregistrer le labyrinthe dans un fichier, comme ça si le programme plante on aura pas à refaire la phase d'exploration, il suffira de récupérer le contenu du fichier.

C'est la prof qui organise la compèt qui nous a dit de faire ca ;)

**Comment by Usanter** [comment]
Save dans backup.txt:
SIZE_X
SIZE_Y
wall[0]
wall[1]
...
wall[n]
