### ISSUE TITLE
Rentrer à la main le labyrinthe

### ISSUE THREAD

**Issue by SneakDiffer** [Usanter/RobotLegoMazeSolver#11]
il faut aussi faire un truc SIMPLE pour rentrer le labyrinthe à la main si notre phase d'exploration plante, ou si on est trop long.

Pour ca vu qu'on connait la taille du lab, il faudrait le faire avec l'IHM, genre sur l'IHM on a le lab et  on a plus qu'à cliqué sur l'IHM ou on veux mettre des murs

**Comment by Usanter** [comment]
J'ai mis Théo et Hugo en assignés car ils ils sont chaud sur Qt. Mais on peux changer.

**Comment by Zarzwick** [comment]
Ce serait utile de nous dire les dimensions de l'arène:
- **nombre** des cases dans les 2 (ou 3 :D) dimensions
- taille des cases

**Comment by SneakDiffer** [comment]
nombre de cases : 23 longueur 11 largeur 
Dimension d'une case 40 / 40 cm

**Comment by Zarzwick** [comment]
Merci, ce qui nous fait donc 253 cases, soit 64,009 cases dans la matrice !

**Comment by Usanter** [comment]
C'est géré coté Ordinateur ça devrais pas prendre longtemps

**Comment by SneakDiffer** [comment]
pour l'IHM, il faut pouvoir rentrer les coordonnées du coin départ / arrivé
coordonnée de la case d'arrivée
taille du labyrinthe ( au cas ou )

**Comment by Zarzwick** [comment]
une bonne base a été push sur c4784ce84b26cdb52677602f623fe0a527497b40

**Comment by Zarzwick** [comment]
le `QPainter` sera probablement remplacé par un `QGraphicsView` dans un futur proche, pour dessiner des **carrés** et des **lignes noires** si mur il y a.

**Comment by Zarzwick** [comment]
J'ai désassigné Théo et moi, je pense que l'issue est plus trop d'actualités, après peut-être j'ai tort.
En plus ça faisait désordre sur github ¯_(ツ)_/¯
