### ISSUE TITLE
Robot

### ISSUE THREAD

**Issue by Usanter** [Usanter/RobotLegoMazeSolver#21]
Création de l'abstraction du robot coté IA

**Comment by Usanter** [comment]
Class robot{
public:
//accesseurs ici 
_int avance();
int tourne();
....._
**OU**
_sendDeplacement(vector<deplacement> listDepl);_
private:
int x;
int y;
int dir;
};

Idée de SD.

**Comment by SneakDiffer** [comment]
Déja pour une case, il faut dire si les 4 murs ont étaient visité ou non. 
Donc un truc genre = - 1 si le murs n'est pas visité.
Pour la SD, je pense qu'on en a pas franchement besoin ? 
Car si on connait la direction envoyé, on peux recupérer direct la case avec la SD représentation, explication : 

courant = 0,0
si on va en haut 
courant = 0,1

Donc pas vraiment besoin de faire une nouvelles SD pour ca.

**Comment by SneakDiffer** [comment]
On envoi au robot la direction : 
#define HAUT 1
#define DROITE 2
#define BAS 3
#define GAUCHE 4

On appelle la fonction nxt_send_message ( HAUT ) ....

**Comment by Usanter** [comment]
Struct robot{
int (ou autre type à voir) id;
int x;
int y;
int dir;
};
