### ISSUE TITLE
Static Connection bluetooth 

### ISSUE THREAD

**Issue by Usanter** [Usanter/RobotLegoMazeSolver#8]
Mettre la connexion bluetooth en "Statique" afin de pouvoir y accéder partout où on l'appelle.

**Comment by Usanter** [comment]
Je propose de crée un singleton pour la connexion (logiquement on a un unique connexion avec le robot)

Lien utile:
[Wiki singleton](https://fr.wikipedia.org/wiki/Singleton_%28patron_de_conception%29)
[Developpez.com](http://come-david.developpez.com/tutoriels/dps/?page=Singleton)

**Comment by SneakDiffer** [comment]
Le socket est déja en static dans le code, il suffit juste d'appeler les fonctions send et receive. Avec un include connection on peut y accéder de partout donc moi je dirai de le laissé comme ca
